internal.lb.uri: http://localhost
spring:
  cloud:
    gateway:
      routes:
        - id: task-microservice
          url: ${internal.lb.uri}:8081
          predicates:
            - Path=/task-service/**
          filters:
            - RewritePath=/task-service/(?<path>.*), /$\{path}